export { default as Header } from './Header'
export { default as Employees } from './EmployeesBlock'
export { default as Categories } from './CategoriesBlock'
export { default as ProfileCard } from './ProfileCard'
export { default as LoadingCategory } from './CategoriesBlock/LoadingBlock'
export { default as LoadingProvider } from './EmployeesBlock/LoadingBlock'